public with sharing class GlobalConstants {
    public static FINAL String OPPSTATUSCLOSEDWON   = 'Closed Won';
    public static FINAL String OPPSTATUSCLOSEDLOST  = 'Closed Lost';
    public static FINAL String OPPSTATUSWINS        = 'Wins';
    public static FINAL String OPPSTATUSLOST        = 'Lost';    
    public static FINAL String OPPSTATUSPIPELINE    = 'Pipeline';    
    public static FINAL String PERIODTYPEYEAR       = 'Year';
}